### ISSUE TITLE
libevent 2.0.21 gets 404 from sunet.dl.sourceforge.net

### ISSUE THREAD

**Issue by poopsock** [elijahpaul/install-transmission#1]
Script cannot finish installing libevent. it gets stuck after retrying this URL 20 times then fails:

>--2015-07-09 11:23:53--  (try:18)  http://sunet.dl.sourceforge.net/project/levent/libevent/libevent-2.0/libevent-2.0.21-stable.tar.gz
>Connecting to sunet.dl.sourceforge.net|8.5.1.40|:80... connected.
>HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
>Retrying.

I changed the URL and version number in the install script:

>wget https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz
>tar xzf libevent-2.0.22-stable.tar.gz
>cd libevent-2.0.22-stable

**Comment by elijahpaul** [comment]
@poopsock Thanks for this. Much appreciated :fist:
